import initClearRefinementsStories from './stories/clear-refinements.stories';
import initCurrentRefinedValuesStories from './stories/current-refined-values.stories';
import initHierarchicalMenuStories from './stories/hierarchical-menu.stories';
import initHitsStories from './stories/hits.stories';
import initHitsPerPageStories from './stories/hits-per-page.stories';
import initInfiniteHitsStories from './stories/infinite-hits.stories';
import initMenuStories from './stories/menu.stories';
import initNumericMenuStories from './stories/numeric-menu.stories';
import initPaginationStories from './stories/pagination.stories';
import initRefinementListStories from './stories/refinement-list.stories';
import initSearchBoxStories from './stories/search-box.stories';
import initSortByStories from './stories/sort-by.stories';
import initRatingMenuStories from './stories/rating-menu.stories';
import initStatsStories from './stories/stats.stories';
import initToggleStories from './stories/toggleRefinement.stories';
import initAutcompleteStories from './stories/autocomplete.stories';

export default () => {
  initClearRefinementsStories();
  initCurrentRefinedValuesStories();
  initHierarchicalMenuStories();
  initHitsStories();
  initHitsPerPageStories();
  initInfiniteHitsStories();
  initMenuStories();
  initNumericMenuStories();
  initPaginationStories();
  initRefinementListStories();
  initSearchBoxStories();
  initSortByStories();
  initRatingMenuStories();
  initStatsStories();
  initToggleStories();
  initAutcompleteStories();
};
