import initClearRefinementsStories from './stories/clear-refinements.stories.js';
import initCurrentRefinedValuesStories from './stories/current-refined-values.stories';
import initHierarchicalMenuStories from './stories/hierarchical-menu.stories';
import initHitsStories from './stories/hits.stories';
import initHitsPerPageSelectorStories from './stories/hits-per-page-selector.stories';
import initInfiniteHitsStories from './stories/infinite-hits.stories';
import initMenuStories from './stories/menu.stories';
import initNumericRefinementListStories from './stories/numeric-refinement-list.stories';
import initNumericSelectorStories from './stories/numeric-selector.stories';
import initPaginationStories from './stories/pagination.stories';
import initPriceRangesStories from './stories/price-ranges.stories';
import initRefinementListStories from './stories/refinement-list.stories';
import initSearchBoxStories from './stories/search-box.stories';
import initSortBySelectorStories from './stories/sort-by-selector.stories';
import initStarRatingStories from './stories/star-rating.stories';
import initStatsStories from './stories/stats.stories';
import initToggleStories from './stories/toggle.stories';
import initAutcompleteStories from './stories/autocomplete.stories';

export default () => {
  initClearRefinementsStories();
  initCurrentRefinedValuesStories();
  initHierarchicalMenuStories();
  initHitsStories();
  initHitsPerPageSelectorStories();
  initInfiniteHitsStories();
  initMenuStories();
  initNumericRefinementListStories();
  initNumericSelectorStories();
  initPaginationStories();
  initPriceRangesStories();
  initRefinementListStories();
  initSearchBoxStories();
  initSortBySelectorStories();
  initStarRatingStories();
  initStatsStories();
  initToggleStories();
  initAutcompleteStories();
};
