import './globals.css';
import 'instantsearch.css/themes/satellite-min.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="AMB0fkgxwBoeRwRG93xQ7IUkmteaFHss6Jz9BBvq7EU"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
