options:
  formatter: stylish
files:
  include: '**/*.scss'
  ignore:
    - 'node_modules/**/*'
    - 'docs/examples/*/main.scss' # Jekyll files requiring front-matter
    - 'docs/css/main.scss' # Jekyll files requiring front-matter
    - 'docs/css/bootstrap/**/*' # Vendor
    - 'docs/css/_syntax-highlighting.scss' # Vendor
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 0
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 1

  # Name Formats
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 1

  # Style Guide
  border-zero: 1
  brace-style: 1
  clean-import-paths: 1
  empty-args: 1
  hex-length: 0
  hex-notation:
    - 2
    -
      style: uppercase
  indentation: 1
  leading-zero: 1
  nesting-depth: 0
  property-sort-order: 0
  quotes: 0
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
