[build]
  command=""" \
    yarn build:ci && \
    yarn website:storybook && \
    yarn website:examples --concurrency=1 && \
    yarn workspace algoliasearch-helper doc
    """
  publish="website"

[build.environment]
  YARN_VERSION = "1.13.0"
