[build]
  command=""" \
    yarn build --ignore='example-*' && \
    yarn website:storybook && \
    yarn website:examples --concurrency=1 && \
    yarn website:specs \
    """
  publish="website"

[build.environment]
  YARN_VERSION = "1.13.0"
