import initAnalyticsStories from './stories/analytics.stories';
import initBreadcrumbStories from './stories/breadcrumb.stories.js';
import initClearRefinementsStories from './stories/clear-refinements.stories';
import initCurrentRefinedValuesStories from './stories/current-refined-values.stories';
import initGeoSearch from './stories/geo-search.stories';
import initHierarchicalMenu from './stories/hierarchical-menu.stories';
import initHitsStories from './stories/hits.stories';
import initHitsPerPageStories from './stories/hits-per-page.stories';
import initInfiniteHitsStories from './stories/infinite-hits.stories';
import initInstantSearchStories from './stories/instantsearch.stories';
import initMenuStories from './stories/menu.stories';
import initMenuSelectStories from './stories/menu-select.stories';
import initNumericRefinementListStories from './stories/numeric-refinement-list.stories';
import initNumericSelectorStories from './stories/numeric-selector.stories';
import initPaginationStories from './stories/pagination.stories';
import initRangeInputStories from './stories/range-input.stories.js';
import initRangeSliderStories from './stories/range-slider.stories';
import initRefinementListStories from './stories/refinement-list.stories';
import initReloadStories from './stories/reload.stories';
import initSearchBoxStories from './stories/search-box.stories';
import initSortByStories from './stories/sort-by.stories';
import initStarRatingStories from './stories/star-rating.stories';
import initStatsStories from './stories/stats.stories';
import initToggleStories from './stories/toggle.stories';
import initConfigureStories from './stories/configure.stories';

export default () => {
  initAnalyticsStories();
  initBreadcrumbStories();
  initClearRefinementsStories();
  initCurrentRefinedValuesStories();
  initGeoSearch();
  initHierarchicalMenu();
  initHitsStories();
  initHitsPerPageStories();
  initInfiniteHitsStories();
  initInstantSearchStories();
  initMenuStories();
  initMenuSelectStories();
  initNumericRefinementListStories();
  initNumericSelectorStories();
  initPaginationStories();
  initRangeInputStories();
  initRangeSliderStories();
  initRefinementListStories();
  initReloadStories();
  initSearchBoxStories();
  initSortByStories();
  initStatsStories();
  initStarRatingStories();
  initToggleStories();
  initConfigureStories();
};
