export * from './getContainerNode';
export * from './isDomElement';
export {
  addWidgetId,
  resetWidgetId,
  capitalize,
  defer,
  createDocumentationLink,
  createDocumentationMessageGenerator,
  TAG_PLACEHOLDER,
  TAG_REPLACEMENT,
  escapeHits,
  escapeFacets,
  escape,
  unescape,
  getHighlightedParts,
  getHighlightFromSiblings,
  getObjectType,
  getPropertyByPath,
  getWidgetAttribute,
  isEqual,
  isFacetRefined,
  isIndexWidget,
  isPlainObject,
  isSpecialClick,
  warnCache,
  deprecate,
  warning,
  noop,
  range,
  createInitArgs,
  createRenderArgs,
  reverseHighlightedParts,
  safelyRunOnBrowser,
  toArray,
  keys,
  uniq,
  createUUID,
  walkIndex,
} from 'instantsearch-core';
