import {
  breadcrumb,
  clearRefinements,
  configure,
  currentRefinements,
  frequentlyBoughtTogether,
  hierarchicalMenu,
  hits,
  hitsPerPage,
  infiniteHits,
  lookingSimilar,
  menu,
  numericMenu,
  pagination,
  rangeInput,
  rangeSlider,
  ratingMenu,
  refinementList,
  relatedProducts,
  searchBox,
  sortBy,
  stats,
  toggleRefinement,
  trendingItems,
} from 'instantsearch.js/es/widgets/index.umd';

export const widgets = {
  'ais.breadcrumb': breadcrumb,
  'ais.clearRefinements': clearRefinements,
  'ais.configure': configure,
  'ais.currentRefinements': currentRefinements,
  'ais.frequentlyBoughtTogether': frequentlyBoughtTogether,
  'ais.hierarchicalMenu': hierarchicalMenu,
  'ais.hits': hits,
  'ais.hitsPerPage': hitsPerPage,
  'ais.infiniteHits': infiniteHits,
  'ais.lookingSimilar': lookingSimilar,
  'ais.menu': menu,
  'ais.numericMenu': numericMenu,
  'ais.pagination': pagination,
  'ais.rangeInput': rangeInput,
  'ais.rangeSlider': rangeSlider,
  'ais.ratingMenu': ratingMenu,
  'ais.refinementList': refinementList,
  'ais.relatedProducts': relatedProducts,
  'ais.searchBox': searchBox,
  'ais.sortBy': sortBy,
  'ais.stats': stats,
  'ais.toggleRefinement': toggleRefinement,
  'ais.trendingItems': trendingItems,
};
