// This folder is used for utility functions that are useful within the InstantSearch Core library and externally from other flavours. Not for internal-only usage. For that the `src/lib/utils` folder should be used.

export * from './addWidgetId';
export * from './capitalize';
export * from './createUUID';
export * from './defer';
export * from './documentation';
export * from './escape-highlight';
export * from './escape-html';
export * from './getHighlightedParts';
export * from './getHighlightFromSiblings';
export * from './getObjectType';
export * from './getPropertyByPath';
export * from './getWidgetAttribute';
export * from './isEqual';
export * from './isFacetRefined';
export * from './isIndexWidget';
export * from './isPlainObject';
export * from './isSpecialClick';
export * from './logger';
export * from './noop';
export * from './range';
export * from './render-args';
export * from './reverseHighlightedParts';
export * from './safelyRunOnBrowser';
export * from './toArray';
export * from './typedObject';
export * from './uniq';
export * from './walkIndex';
